server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: always

spring:
  application:
    name: catalog-service
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/ms_demo
    username: ms_user
    password: ms_pass
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
